[package]
name = "pareen"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"

[dev-dependencies]
assert_approx_eq = "1.0"
gnuplot = "0.0.32"
